name 'dwerder-redis'
version '1.2.0'
source 'git clone https://github.com/echocat/puppet-redis.git'
author 'Daniel Werdermann'
license 'Mozilla Public License Version 2.0'
summary 'Install and configure redis and sentinel from repo or source'
description 'This module installs redis and can configure multiple instances of redis and sentinel.'
project_page 'https://github.com/echocat/puppet-redis'
